"""empty message

Revision ID: b3457bd34ecd
Revises: 
Create Date: 2025-02-07 15:55:20.317792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b3457bd34ecd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestreamers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('override', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('filters', sa.JSON(), nullable=True))
        batch_op.drop_column('overwrite')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestreamers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overwrite', sqlite.JSON(), nullable=True))
        batch_op.drop_column('filters')
        batch_op.drop_column('override')

    # ### end Alembic commands ###
