"""empty message

Revision ID: fe9bd3c08df6
Revises: b3457bd34ecd
Create Date: 2025-02-09 12:02:47.976234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9bd3c08df6'
down_revision: Union[str, None] = 'b3457bd34ecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestreamers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filters', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestreamers', schema=None) as batch_op:
        batch_op.drop_column('filters')

    # ### end Alembic commands ###
